export const MIN_USER_LOGIN_LENGTH = 3;
export const MAX_USER_LOGIN_LENGTH = 20;
export const MIN_USER_PASSWORD_LENGTH = 4;
export const MAX_USER_PASSWORD_LENGTH = 45;


export const MAX_THEME_TITLE_LENGTH = 20;
export const MAX_THEME_DESCRIPTION_LENGTH = 120;